### ISSUE TITLE
Create a Contributors.md file

### ISSUE THREAD

**Issue by clarkeben** [Shubham0812/HabitTracker_UI#11]
## Requirements
Add a new markdown (.md) file to the [documentation folder](https://github.com/Shubham0812/HabitTracker_UI/tree/main/docs) that lists all contributors within the project. Consider the optimum style, ideally, the page should contain:
* Information about the project
* List the user's name (linking to their Github - use placeholders for now)
* Contain information about how users can get involved in the project 

An[ existing template exists](https://github.com/cezaraugusto/github-template-guidelines/blob/master/.github/CONTRIBUTORS.md) for this, though a table might be better suited. 

| Contributor | Position | Social links      |
|-------------|----------|-------------------|
| Name one    | ✨        | Twitter Instagram |
| Name two    | 📖        | Twitter           |
| Name three  | 💻        | Twitter Instagram |

## Solution
1. Create file
2. Create sections
3. Populate sections

**Comment by IgorChernyshov** [comment]
Hi there, I've opened a PR regarding this issue
